"""drop ex_num column

Revision ID: 530df5125394
Revises: 9f52d20a453a
Create Date: 2023-04-15 20:47:38.925570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530df5125394'
down_revision = '9f52d20a453a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'ex_num')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('ex_num', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
